import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

// eslint-config-next 15.x is still eslintrc-style (no flat-config export), so it
// is bridged through FlatCompat. This is the same wiring create-next-app emits.
// `.mjs` because package.json has no "type": "module".
const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "next-env.d.ts", // generated by Next, not ours to lint
      "src/fonts/**", // binary .woff2
    ],
  },
  // core-web-vitals = the Next rules that map to real user-facing problems
  // (raw <img>, sync <script>, missing preconnect …) at error level rather than
  // warn, plus react-hooks. `next/typescript` layers on typescript-eslint.
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
